version: '3.8'

services:
  metrics:
    build:
      context: ./src/backend/metrics/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - metrics_network
    environment:
      - JIRA_DOMAIN=https://pierre01.atlassian.net
      - JIRA_API_TOKEN=ATATT3xFfGF0tbyCe4UTMTq5aURfgL_lStdPZt91jo4NvWdHdpz_IJfJYZzCZoqslKL8GXbCsyTsLbsgESkhgFqcGFjemQzpaZnUiAKPcKckNfbV0t2WAwte9tRAhmhPKGadevB5pZ0Uur56TqOPMRb4-eXcrs1_uxn4jh6AL28g-_126EZyxK0=41606B8F
      - JIRA_EMAIL=pierre.nadal@me.com
      - JIRA_PROJECT=RPCS

  database:
    build:
      context: ./src/backend/database
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - db_network
    environment:
      - MONGODB_URI=mongodb+srv://yourentertainmentscompagny:BLX0bKwtZTwqTm5a@playground.mngkvjq.mongodb.net/yourPieces?retryWrites=true&w=majority&appName=Playground

  dockerserviceclient:
    build:
      context: ./src/backend/dockerserviceclient
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - metrics_network
      - db_network
    depends_on:
      - metrics
      - database

networks:
  db_network:
    driver: bridge
  metrics_network:
    driver: bridge
